package com.myspace.stage1;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Approval")
public class Approval implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Management Board Approval")
	private boolean managementBoard;
	@org.kie.api.definition.type.Label(value = "Delegated Sanction")
	private boolean delegatedSanction;
	@org.kie.api.definition.type.Label(value = "Specific Sanction")
	private boolean specificSanction;

	public Approval() {
	}

	public boolean isManagementBoard() {
		return this.managementBoard;
	}

	public void setManagementBoard(boolean managementBoard) {
		this.managementBoard = managementBoard;
	}

	public boolean isDelegatedSanction() {
		return this.delegatedSanction;
	}

	public void setDelegatedSanction(boolean delegatedSanction) {
		this.delegatedSanction = delegatedSanction;
	}

	public boolean isSpecificSanction() {
		return this.specificSanction;
	}

	public void setSpecificSanction(boolean specificSanction) {
		this.specificSanction = specificSanction;
	}

	public Approval(boolean managementBoard, boolean delegatedSanction,
			boolean specificSanction) {
		this.managementBoard = managementBoard;
		this.delegatedSanction = delegatedSanction;
		this.specificSanction = specificSanction;
	}

}