package com.myspace.stage1;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("CompetitionRequest")
public class CompetitionRequest implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Competition Title")
	private java.lang.String competitionTitle;
	@org.kie.api.definition.type.Label("Requesting Division")
	private java.lang.String requestingDivision;
	@org.kie.api.definition.type.Label("Post")
	private com.myspace.stage1.Post post;
	@org.kie.api.definition.type.Label("Timeframe")
	private com.myspace.stage1.Timeframe timeframe;
	@org.kie.api.definition.type.Label("Principal Stakeholder")
	private java.lang.String stakeholder;
	@org.kie.api.definition.type.Label("Candidate Liason")
	private java.lang.String liason;
	@org.kie.api.definition.type.Label("Other Relevant Information")
	private java.lang.String other;

	@org.kie.api.definition.type.Label(value = "Irish Language Requirement")
	private java.lang.Boolean languageRequirement;

	public CompetitionRequest() {
	}

	public java.lang.String getCompetitionTitle() {
		return this.competitionTitle;
	}

	public void setCompetitionTitle(java.lang.String competitionTitle) {
		this.competitionTitle = competitionTitle;
	}

	public java.lang.String getRequestingDivision() {
		return this.requestingDivision;
	}

	public void setRequestingDivision(java.lang.String requestingDivision) {
		this.requestingDivision = requestingDivision;
	}

	public com.myspace.stage1.Post getPost() {
		return this.post;
	}

	public void setPost(com.myspace.stage1.Post post) {
		this.post = post;
	}

	public com.myspace.stage1.Timeframe getTimeframe() {
		return this.timeframe;
	}

	public void setTimeframe(com.myspace.stage1.Timeframe timeframe) {
		this.timeframe = timeframe;
	}

	public java.lang.String getStakeholder() {
		return this.stakeholder;
	}

	public void setStakeholder(java.lang.String stakeholder) {
		this.stakeholder = stakeholder;
	}

	public java.lang.String getLiason() {
		return this.liason;
	}

	public void setLiason(java.lang.String liason) {
		this.liason = liason;
	}

	public java.lang.String getOther() {
		return this.other;
	}

	public void setOther(java.lang.String other) {
		this.other = other;
	}

	public java.lang.Boolean getLanguageRequirement() {
		return this.languageRequirement;
	}

	public void setLanguageRequirement(java.lang.Boolean languageRequirement) {
		this.languageRequirement = languageRequirement;
	}

	public CompetitionRequest(java.lang.String competitionTitle,
			java.lang.String requestingDivision, com.myspace.stage1.Post post,
			com.myspace.stage1.Timeframe timeframe,
			java.lang.String stakeholder, java.lang.String liason,
			java.lang.String other, java.lang.Boolean languageRequirement) {
		this.competitionTitle = competitionTitle;
		this.requestingDivision = requestingDivision;
		this.post = post;
		this.timeframe = timeframe;
		this.stakeholder = stakeholder;
		this.liason = liason;
		this.other = other;
		this.languageRequirement = languageRequirement;
	}

}