package com.myspace.stage1;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CompetitionRequest implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public CompetitionRequest() {
    }




}