package com.myspace.stage1;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("HRStrategyApproval")
public class HRStrategyApproval implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Competition Title")
	private java.lang.String competitionTitle;
	@org.kie.api.definition.type.Label("Competition Type")
	private java.lang.String competitionType;
	@org.kie.api.definition.type.Label("Approval")
	private com.myspace.stage1.Approval approval;
	@org.kie.api.definition.type.Label("Internal Mobility")
	private boolean internalMobility;
	@org.kie.api.definition.type.Label("Other Relevant Information")
	private java.lang.String other;

	@org.kie.api.definition.type.Label("Approval Granted")
	private java.lang.String approvalGranted;

	@org.kie.api.definition.type.Label(value = "Post")
	private com.myspace.stage1.Post post;

	public HRStrategyApproval() {
	}

	public java.lang.String getCompetitionTitle() {
		return this.competitionTitle;
	}

	public void setCompetitionTitle(java.lang.String competitionTitle) {
		this.competitionTitle = competitionTitle;
	}

	public java.lang.String getCompetitionType() {
		return this.competitionType;
	}

	public void setCompetitionType(java.lang.String competitionType) {
		this.competitionType = competitionType;
	}

	public com.myspace.stage1.Approval getApproval() {
		return this.approval;
	}

	public void setApproval(com.myspace.stage1.Approval approval) {
		this.approval = approval;
	}

	public boolean isInternalMobility() {
		return this.internalMobility;
	}

	public void setInternalMobility(boolean internalMobility) {
		this.internalMobility = internalMobility;
	}

	public java.lang.String getOther() {
		return this.other;
	}

	public void setOther(java.lang.String other) {
		this.other = other;
	}

	public java.lang.String getApprovalGranted() {
		return this.approvalGranted;
	}

	public void setApprovalGranted(java.lang.String approvalGranted) {
		this.approvalGranted = approvalGranted;
	}

	public com.myspace.stage1.Post getPost() {
		return this.post;
	}

	public void setPost(com.myspace.stage1.Post post) {
		this.post = post;
	}

	public HRStrategyApproval(java.lang.String competitionTitle,
			java.lang.String competitionType,
			com.myspace.stage1.Approval approval, boolean internalMobility,
			java.lang.String other, java.lang.String approvalGranted,
			com.myspace.stage1.Post post) {
		this.competitionTitle = competitionTitle;
		this.competitionType = competitionType;
		this.approval = approval;
		this.internalMobility = internalMobility;
		this.other = other;
		this.approvalGranted = approvalGranted;
		this.post = post;
	}

}