package com.myspace.stage1;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("HRStrategyApproval")
public class HRStrategyApproval implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Competition Title")
	private java.lang.String competitionTitle;
	@org.kie.api.definition.type.Label(value = "Post Information")
	private com.myspace.stage1.PostInfo postInfo;
	@org.kie.api.definition.type.Label(value = "Competition Type")
	private java.lang.String competitionType;
	@org.kie.api.definition.type.Label(value = "Approval")
	private com.myspace.stage1.Approval approval;
	@org.kie.api.definition.type.Label(value = "Immediate Vacancies")
	private java.lang.Integer immediateVacancies;
	@org.kie.api.definition.type.Label(value = "Estimated Vacancies")
	private java.lang.Integer estimatedVacancies;
	@org.kie.api.definition.type.Label(value = "Location of Posts")
	private java.lang.String location;
	@org.kie.api.definition.type.Label(value = "Internal Mobility")
	private boolean internalMobility;
	@org.kie.api.definition.type.Label(value = "Other Relevant Information")
	private java.lang.String other;

	public HRStrategyApproval() {
	}

	public java.lang.String getCompetitionTitle() {
		return this.competitionTitle;
	}

	public void setCompetitionTitle(java.lang.String competitionTitle) {
		this.competitionTitle = competitionTitle;
	}

	public com.myspace.stage1.PostInfo getPostInfo() {
		return this.postInfo;
	}

	public void setPostInfo(com.myspace.stage1.PostInfo postInfo) {
		this.postInfo = postInfo;
	}

	public java.lang.String getCompetitionType() {
		return this.competitionType;
	}

	public void setCompetitionType(java.lang.String competitionType) {
		this.competitionType = competitionType;
	}

	public com.myspace.stage1.Approval getApproval() {
		return this.approval;
	}

	public void setApproval(com.myspace.stage1.Approval approval) {
		this.approval = approval;
	}

	public java.lang.Integer getImmediateVacancies() {
		return this.immediateVacancies;
	}

	public void setImmediateVacancies(java.lang.Integer immediateVacancies) {
		this.immediateVacancies = immediateVacancies;
	}

	public java.lang.Integer getEstimatedVacancies() {
		return this.estimatedVacancies;
	}

	public void setEstimatedVacancies(java.lang.Integer estimatedVacancies) {
		this.estimatedVacancies = estimatedVacancies;
	}

	public java.lang.String getLocation() {
		return this.location;
	}

	public void setLocation(java.lang.String location) {
		this.location = location;
	}

	public boolean isInternalMobility() {
		return this.internalMobility;
	}

	public void setInternalMobility(boolean internalMobility) {
		this.internalMobility = internalMobility;
	}

	public java.lang.String getOther() {
		return this.other;
	}

	public void setOther(java.lang.String other) {
		this.other = other;
	}

	public HRStrategyApproval(java.lang.String competitionTitle,
			com.myspace.stage1.PostInfo postInfo,
			java.lang.String competitionType,
			com.myspace.stage1.Approval approval,
			java.lang.Integer immediateVacancies,
			java.lang.Integer estimatedVacancies, java.lang.String location,
			boolean internalMobility, java.lang.String other) {
		this.competitionTitle = competitionTitle;
		this.postInfo = postInfo;
		this.competitionType = competitionType;
		this.approval = approval;
		this.immediateVacancies = immediateVacancies;
		this.estimatedVacancies = estimatedVacancies;
		this.location = location;
		this.internalMobility = internalMobility;
		this.other = other;
	}

}