package com.myspace.stage1;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("PostType")
public class postType implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Post Term")
	private java.lang.String postTerm;
	@org.kie.api.definition.type.Label(value = "Time Type")
	private java.lang.String timeType;
	@org.kie.api.definition.type.Label(value = "Vacancies")
	private java.lang.String vacancies;

	public postType() {
	}

	public java.lang.String getPostTerm() {
		return this.postTerm;
	}

	public void setPostTerm(java.lang.String postTerm) {
		this.postTerm = postTerm;
	}

	public java.lang.String getTimeType() {
		return this.timeType;
	}

	public void setTimeType(java.lang.String timeType) {
		this.timeType = timeType;
	}

	public java.lang.String getVacancies() {
		return this.vacancies;
	}

	public void setVacancies(java.lang.String vacancies) {
		this.vacancies = vacancies;
	}

	public postType(java.lang.String postTerm, java.lang.String timeType,
			java.lang.String vacancies) {
		this.postTerm = postTerm;
		this.timeType = timeType;
		this.vacancies = vacancies;
	}

}