package com.myspace.stage1;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Post")
public class Post implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Post Information")
	private com.myspace.stage1.PostInfo postInfo;
	@org.kie.api.definition.type.Label(value = "Level of Post")
	private java.lang.String postLevel;
	@org.kie.api.definition.type.Label(value = "Number of Immediate Posts")
	private java.lang.Integer immediatePosts;
	@org.kie.api.definition.type.Label(value = "Number of Estimated Posts")
	private java.lang.Integer estimatedPosts;
	@org.kie.api.definition.type.Label(value = "Location of Posts")
	private java.lang.String location;
	@org.kie.api.definition.type.Label(value = "Irish Language Requirement")
	private boolean languageRequirement;

	public Post() {
	}

	public com.myspace.stage1.PostInfo getPostInfo() {
		return this.postInfo;
	}

	public void setPostInfo(com.myspace.stage1.PostInfo postInfo) {
		this.postInfo = postInfo;
	}

	public java.lang.String getPostLevel() {
		return this.postLevel;
	}

	public void setPostLevel(java.lang.String postLevel) {
		this.postLevel = postLevel;
	}

	public java.lang.Integer getImmediatePosts() {
		return this.immediatePosts;
	}

	public void setImmediatePosts(java.lang.Integer immediatePosts) {
		this.immediatePosts = immediatePosts;
	}

	public java.lang.Integer getEstimatedPosts() {
		return this.estimatedPosts;
	}

	public void setEstimatedPosts(java.lang.Integer estimatedPosts) {
		this.estimatedPosts = estimatedPosts;
	}

	public java.lang.String getLocation() {
		return this.location;
	}

	public void setLocation(java.lang.String location) {
		this.location = location;
	}

	public boolean isLanguageRequirement() {
		return this.languageRequirement;
	}

	public void setLanguageRequirement(boolean languageRequirement) {
		this.languageRequirement = languageRequirement;
	}

	public Post(com.myspace.stage1.PostInfo postInfo,
			java.lang.String postLevel, java.lang.Integer immediatePosts,
			java.lang.Integer estimatedPosts, java.lang.String location,
			boolean languageRequirement) {
		this.postInfo = postInfo;
		this.postLevel = postLevel;
		this.immediatePosts = immediatePosts;
		this.estimatedPosts = estimatedPosts;
		this.location = location;
		this.languageRequirement = languageRequirement;
	}

}