package com.myspace.stage1;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("PostInfo")
public class PostInfo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Post Term")
	private java.lang.String postTerm;
	@org.kie.api.definition.type.Label(value = "Post Type")
	private java.lang.String postType;
	@org.kie.api.definition.type.Label(value = "Vacancies")
	private java.lang.String vacancies;

	public PostInfo() {
	}

	public java.lang.String getPostTerm() {
		return this.postTerm;
	}

	public void setPostTerm(java.lang.String postTerm) {
		this.postTerm = postTerm;
	}

	public java.lang.String getPostType() {
		return this.postType;
	}

	public void setPostType(java.lang.String postType) {
		this.postType = postType;
	}

	public java.lang.String getVacancies() {
		return this.vacancies;
	}

	public void setVacancies(java.lang.String vacancies) {
		this.vacancies = vacancies;
	}

	public PostInfo(java.lang.String postTerm, java.lang.String postType,
			java.lang.String vacancies) {
		this.postTerm = postTerm;
		this.postType = postType;
		this.vacancies = vacancies;
	}

}