package com.myspace.stage1;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("StageCompleted")
public class StageCompleted implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Stage Completed")
	private java.lang.Boolean completed;

	public StageCompleted() {
	}

	public java.lang.Boolean getCompleted() {
		return this.completed;
	}

	public void setCompleted(java.lang.Boolean completed) {
		this.completed = completed;
	}

	public StageCompleted(java.lang.Boolean completed) {
		this.completed = completed;
	}

}