package com.myspace.stage1;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Timeframe")
public class Timeframe implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Quarter")
	private java.lang.String quarter;
	@org.kie.api.definition.type.Label(value = "Year")
	private java.lang.Integer year;

	public Timeframe() {
	}

	public java.lang.String getQuarter() {
		return this.quarter;
	}

	public void setQuarter(java.lang.String quarter) {
		this.quarter = quarter;
	}

	public java.lang.Integer getYear() {
		return this.year;
	}

	public void setYear(java.lang.Integer year) {
		this.year = year;
	}

	public Timeframe(java.lang.String quarter, java.lang.Integer year) {
		this.quarter = quarter;
		this.year = year;
	}

}